### ISSUE TITLE
Gameplay addition n°5: Explosive Car

### ISSUE THREAD

**Issue by MartinCHTITI** [l0th3r/TD-Template#11]
We would like to add an enemy unit that explodes. Would it be possible to make a unit destroy itself after an attack ?

**Comment by l0th3r** [comment]
Yes of course, I would like you to specify the behaviour with a specification of every new mechanics added

**Comment by MartinCHTITI** [comment]
Apologies for late response.

The unit will spawn alone. The player should be warned in advance of its arrival. It moves fast, has little health and go straight to the objective. If it reaches it, it will explods, severly damaging the objective. The unit will be destroy in the process.

By the way, we must finish our project for around June 5, so we would like to know if you will be able to incude every addition we requested, and if not which can be included.

Thanks for your attention.

**Comment by l0th3r** [comment]
Hello, thank you for your answer.
I understand, I will need to check with you about how to add visual effects since it's not included in the template.
It is really makable, you can already plan to set the speed, the health amount, the fact that it reach only the objective.

We only need to add the fact that it destroy on attack. So it will be added before the June 5.

**Comment by MartinCHTITI** [comment]
That's good, thank you.
