### ISSUE TITLE
plugin issues

### ISSUE THREAD

**Issue by FlorianJON** [l0th3r/TD-Template#5]
Dear Cosmo,

I had a problem today when I tried to open the template, both the one from patch 1 and the one from milestone final, an error message appears, while Martin doesn't have this problem and on my other pc it worked. Could you please explain or look at what it is. 
![image](https://user-images.githubusercontent.com/98846308/168312614-ce84010d-cfd9-4f23-a434-621d7d399b5b.png)

**Comment by l0th3r** [comment]
Hello, Thank you for submitting this issue. For the Tower Defense Template, no extarnal plugins have been used. When working on the project, I do not think that I used any features of the Bridge plugin. I think you can try to disable it and continue by pressing `Yes` on the window. The _Quixel Bridge_ plugin is not used by the template, having it disabled should not cause any issue with the template. Though if you really need it, I would reconsider to reinstall the Unreal Engine version you use, this plugin is installed by default with Unreal Engine. I will let the issue opened until you can confirm that you can work properly. Thank you to awnser when your problem is fixed.

**Comment by FlorianJON** [comment]
Hello, I encounter an other problem that doesn't come from the template so I can't say if it's a positive or negative answer to the first problem, I'll keep you informed.

**Comment by FlorianJON** [comment]
Ok, so I found out starting the template, on UE5 but now I can't load the map, I only downloaded the patch1 zip, so I was thinking that it could be because I didn't update the milestone_finale file, here is the message I get when I launch it. 
![image](https://user-images.githubusercontent.com/98846308/168336964-34a1c621-2765-4a45-9405-d013d3ab2020.png)

**Comment by l0th3r** [comment]
Hello. I never encountered this issue. Did you tried to remove your project and restart from the last time it was working ?
If it's not working we could do a meeting to try to fix this together, I will need more informations and It would be too long to ask here all the time sadly. Keep me updated.

**Comment by FlorianJON** [comment]
Sorry, I was busy yesterday, to answer you, I tried as you said and it still didn't work, I guess it will be complicated to solve this problem during a meet up because the isssue is on the pc I have at home, on my laptop, the last time it worked correctly. Maybe we could do a video call.

**Comment by FlorianJON** [comment]
Hello,
It seems to be a problem depending of the computer, because on my laptop it works correctly but I still have the problem with path that stop on a random tile of the path, at home, I have the black screen with nothing on unreal and on the computer of the school it works well.
